baseURL = "https://baotrinh9707-coder.github.io/"
locale = 'en-us'
title = 'My Project'
theme = "reimu"

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 3    

  [params]
  avatar = "/images/avatar.jpg"
  author = "Trình"
  subtitle = "UIT Student"
  description = "UIT Student"

[params.footer]
  since = 2026